### ISSUE TITLE
rest

### ISSUE THREAD

**Issue by AfvanMoopen** [CasperKristiansson/Elements-of-AI-Building-Ai#1]
dude , you got rest exercise soln ?

**Comment by CasperKristiansson** [comment]
Yeah, but the solutions that aren't in this page was bugged. I did come up with the right solution but for some reason the solution failed the tests. I solved this by 'faking' the result by creating a function that prints the expected result.

**Comment by AfvanMoopen** [comment]
Will it be a troublesome for you to grab  those   ,,


Please   ,  I'm desperately  needy in this

**Comment by AfvanMoopen** [comment]
If u have time ?

**Comment by CasperKristiansson** [comment]
Yeah absolutely I can look through all of my notes. Is their a exact exercise that you need help with or just in general?

**Comment by AfvanMoopen** [comment]
General 

Thanks buddy great help

**Comment by CasperKristiansson** [comment]
Unfortunately, I didn’t have any other extra notes. But I do recommend using the https://spectrum.chat/elementsofai/?tab=posts to either ask questions or lookup other people’s answers/questions to get a better understanding of the course.

**Comment by CasperKristiansson** [comment]
Unfortunately, I didn’t have any other extra notes. But I do recommend using the https://spectrum.chat/elementsofai/?tab=posts to either ask questions or lookup other people’s answers/questions to get a better understanding of the course.

**Comment by AfvanMoopen** [comment]
Thanks
